### PR TITLE
[Proposal] Feat/circuit interop

### PR DESCRIPTION
**Pull request by dryajov**
adding priorities for transports

Related PR:
https://github.com/libp2p/js-libp2p-swarm/pull/217

### CODE REVIEW

**Comment by diasdavid** [comment]
@dryajov Can you explain what you are trying to achieve with priorities? This is more than what relay should try to achieve. I don't see a necessity for it right now.

**Comment by dryajov** [comment]
The basic requirement is to be able to dial on certain protocols over others. 

Right now, when dialing happens, all the transports are tried in sequence in whatever order they happened to be returned by the `const tKeys = swarm.availableTransports(pi)`. I want to be able to push a transport (i.e. `Circuit`) to be tried last, or after other transports have been tried. The `priority` property would allow for this as I'm sorting the transports based on it in the `availableTransports` method.

The requirement for circuit (and I might be a bit off on this one) is to be able to dial on circuit addresses only if all else failed. In this case, I'm setting all transports to a priority of `1` and `Circuit` to `100`. This allows me to push it to the end of the list of available transports.

IMHO, this is a useful feature to have.

**Comment by dryajov** [comment]
@diasdavid  Alternatively or in addition to this, we could also allow priority be controlled from the config as well, so that we can choose which transports are preferred based on environment conditions.

**Comment by diasdavid** [comment]
Going to skip this, for now.

**Pull request closed without merging**
